spring:
  application:
    name: 'user-service'
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
  profiles:
    active: 'all'
  config:
    import: 'configserver:http://localhost:8061'
server:
  error:
    include-message: always
    include-stacktrace: never
  port: 8050
