spring:
  application:
    name: 'user-service'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: 'all'
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/user'
server:
  error:
    include-message: always
    include-stacktrace: never
  port: 8050
